// Copyright (c) 2026 Lark Technologies Pte. Ltd.
// SPDX-License-Identifier: MIT

package sheets

import (
	_ "embed"
	"encoding/json"
	"fmt"
	"sync"

	"github.com/larksuite/cli/shortcuts/common"
)

// ─── flag definitions, sourced from sheet-skill-spec ───────────────────
//
// data/flag-defs.json is the canonical, full definition of every CLI flag
// (name, type, default, desc, enum, input, hidden, required, kind),
// generated by sheet-skill-spec's sync script. We embed it and build each
// shortcut's []common.Flag from it at assembly time, so flag metadata never
// has to be hand-written in Go.
//
// Flags with kind == "system" (--dry-run, --yes, ...) are NOT materialized
// here: the framework auto-injects them based on Risk / DryRun / HasFormat.
// Do not hand-edit data/flag-defs.json; regenerate via the sync script.

//go:embed data/flag-defs.json
var flagDefsJSON []byte

type flagDef struct {
	Name     string   `json:"name"`
	Kind     string   `json:"kind"`     // "public" | "own" | "system"
	Type     string   `json:"type"`     // string | bool | int | int64 | float64 | string_array | string_slice
	Required string   `json:"required"` // "required" | "optional" | "xor"
	Desc     string   `json:"desc"`
	Default  string   `json:"default"`
	Hidden   bool     `json:"hidden"`
	Enum     []string `json:"enum"`
	Input    []string `json:"input"`
}

type commandDef struct {
	Risk  string    `json:"risk"`
	Flags []flagDef `json:"flags"`
}

var (
	flagDefsOnce sync.Once
	flagDefs     map[string]commandDef
	flagDefsErr  error
)

func loadFlagDefs() (map[string]commandDef, error) {
	flagDefsOnce.Do(func() {
		flagDefs = make(map[string]commandDef)
		if err := json.Unmarshal(flagDefsJSON, &flagDefs); err != nil {
			flagDefsErr = fmt.Errorf("flag-defs.json: %w", err)
		}
	})
	return flagDefs, flagDefsErr
}

// flagsFor builds the []common.Flag for a shortcut command directly from
// flag-defs.json. System-kind flags are skipped (the framework injects
// them). Panics if the command is absent or the JSON is malformed — this
// is a build-time data contract, so a missing entry is a programming error
// surfaced loudly at startup rather than a silent empty flag set.
func flagsFor(command string) []common.Flag {
	defs, err := loadFlagDefs()
	if err != nil {
		panic(fmt.Sprintf("sheets: %v", err))
	}
	spec, ok := defs[command]
	if !ok {
		panic(fmt.Sprintf("sheets: no flag-defs.json entry for %q", command))
	}
	out := make([]common.Flag, 0, len(spec.Flags))
	for _, df := range spec.Flags {
		if df.Kind == "system" {
			continue
		}
		out = append(out, common.Flag{
			Name:     df.Name,
			Type:     df.Type,
			Default:  df.Default,
			Desc:     df.Desc,
			Hidden:   df.Hidden,
			Required: df.Required == "required",
			Enum:     df.Enum,
			Input:    df.Input,
		})
	}
	return out
}
